version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - database
      
      - say-hello:
          filters:
            branches:
              only:
                dev
