version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
            name: Setup custom environment variables
            command: echo 'export CODECOV_TOKEN="a0e970a4-2e77-47e5-96ad-3c7534f83949"' >> $BASH_ENV
      - run: mvn test
      - store_artifacts:
          path: target/site/jacoco/index.html
      - codecov/upload:
          file: './coverage/cover.xml'
          token: a0e970a4-2e77-47e5-96ad-3c7534f83949

workflows:
  version: 2

  build:
    jobs:
      - test
