version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: target/site/jacoco/index.html
    after_success:
      - run: <(curl -s https://codecov.io/bash)
workflows:
  version: 2

  test-with-store-artifacts:
    jobs:
      - test
