version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test-tictactoe:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: echo 'export CODECOV_TOKEN="a0e970a4-2e77-47e5-96ad-3c7534f83949"' >> $BASH_ENV
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: pytest --cov --cov-report xml tests/
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-tictactoe
