USE `db_tourney_server`;

DROP TRIGGER IF EXISTS `ADDRESS_AFTER_INSERT`;
DROP TRIGGER IF EXISTS `AGENT_AFTER_INSERT`;
DROP TRIGGER IF EXISTS `GAME_AFTER_INSERT`;
DROP TRIGGER IF EXISTS `TOURNAMENT_AFTER_INSERT`;
DROP TRIGGER IF EXISTS `MATCH_LOG_AFTER_INSERT`;

DELIMITER //

CREATE TRIGGER `ADDRESS_AFTER_INSERT` AFTER INSERT ON `ADDRESS` FOR EACH ROW
BEGIN
  CALL set_new_id(NEW.ADDRESS_ID);
END //

CREATE TRIGGER `AGENT_AFTER_INSERT` AFTER INSERT ON `AGENT` FOR EACH ROW
BEGIN
	CALL set_new_id(NEW.AGENT_ID);
END //

CREATE TRIGGER `GAME_AFTER_INSERT` AFTER INSERT ON `GAME` FOR EACH ROW
BEGIN
	CALL set_new_id(NEW.GAME_ID);
END //

CREATE TRIGGER `TOURNAMENT_AFTER_INSERT` AFTER INSERT ON `TOURNAMENT` FOR EACH ROW
BEGIN
	CALL set_new_id(NEW.TOURNAMENT_ID);
END //

CREATE TRIGGER `MATCH_LOG_AFTER_INSERT` AFTER INSERT ON `MATCH_LOG` FOR EACH ROW
BEGIN
	CALL set_new_id(NEW.MATCH_LOG_ID);
END //

DELIMITER ;